"""empty message

Revision ID: a9c416fea0ac
Revises: 
Create Date: 2017-12-20 02:06:02.295073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c416fea0ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('patronymic', sa.String(length=80), nullable=True),
    sa.Column('subdivision_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subdivision_id'], ['subdivision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_accounting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kindergarten_id', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('patronymic', sa.String(length=80), nullable=True),
    sa.Column('payment_sum', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['kindergarten_id'], ['kindergarten.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.INTEGER(), nullable=True),
    sa.Column('number_of_visiting_days', sa.INTEGER(), nullable=True),
    sa.Column('child_accounting_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['child_accounting_id'], ['child_accounting.id'], ),
    sa.ForeignKeyConstraint(['month_id'], ['month.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_visits')
    op.drop_table('child_accounting')
    op.drop_table('parents')
    # ### end Alembic commands ###
